name: me
description: Kseniia Flutter developer. Contacts and information
version: 2.2.3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: 3.0.7+1
  url_launcher: 6.3.1
  flutter_gen: 5.10.0
  flutter_svg: 2.1.0
  responsive_framework: 1.5.1
  firebase_core: 3.13.0
  firebase_storage: 12.4.5
  cloud_firestore: 5.6.7
  rive: 0.13.20
  go_router: 15.1.2
  dropdown_button2: 2.3.9
  flutter_native_splash: 2.4.6
  cached_network_image: 3.4.1
  video_player: 2.9.5
  flutter_markdown: 0.7.7+1
  http: ^1.4.0
  markdown: 7.3.0
  provider: 6.1.5
  collection: 1.19.1
  slang_flutter: 4.7.0
  shared_preferences: 2.5.3
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  slang_build_runner: 4.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900


flutter_gen:
  output: lib/generated/
  line_length: 80
  null_safety: true
  integrations:
    flutter_svg: true