name: me
description: Kseniia Flutter developer. Contacts and information
version: 1.0.4+6

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.3
  url_launcher: 6.1.14
  flutter_gen: 5.3.1
  flutter_svg: 2.0.7
  responsive_framework: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700


flutter_gen:
  output: lib/generated/
  line_length: 80
  null_safety: true
  integrations:
    flutter_svg: true