name: me
description: Kseniia Flutter developer. Contacts and information
version: 1.1.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.7
  url_launcher: 6.3.1
  flutter_gen: 5.8.0
  flutter_svg: 2.0.10+1
  responsive_framework: 1.1.1
  firebase_core: 3.6.0
  firebase_storage: 12.3.4
  rive: 0.13.15
  go_router: 14.3.0
  dropdown_button2: 2.3.9
  flutter_native_splash: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.13
  flutter_gen_runner: 5.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900


flutter_gen:
  output: lib/generated/
  line_length: 80
  null_safety: true
  integrations:
    flutter_svg: true